### PR TITLE
chapter 2 sample tests and little refactor

### PR DESCRIPTION
**Pull request by dnvriend**
I have created tests for the akka samples for chapter 2 (great work btw) :) and did some small refactoring to make the actors testable.

### CODE REVIEW

**Comment by cmbaxter** [comment]
Hey Dennis.  This looks good.  Thanks for cleaning up and adding the test coverage.  I will merge this in tonight.

**Comment by cmbaxter** [comment]
Hey Dennis, before I merge this in, I just wanted to ask a quick question.  What was the reasoning for changing logback to use a console output.  I know it's easier to deal with vs tailing the file but I was trying to setup the app as one would when using it in prod and I don't ever use the console appended in prod.  If we are going to use console logging then it's simpler to just remove the 

`loggers = ["akka.event.slf4j.Slf4jLogger"]`

setting and let it use the default behavior of logging to the console.  Thoughts?

**Comment by dnvriend** [comment]
Hi Chris, Good point. Most often when 'containerizing' applications using Docker and running them, the logs go to the System.out and System.err. The running docker container can use a [logging driver](https://docs.docker.com/engine/admin/logging/overview/) like eg. syslog to send the log lines to logstash daemon as described [here](http://nathanleclaire.com/blog/2015/04/27/automating-docker-logging-elasticsearch-logstash-kibana-and-logspout/). This way all logging can be collected at a central location and when routed to an ElasticSearch, indexed and queried using Kibana. Why configure akka.event.slf4j.Slf4jLogger, to declare which loggers/level we want to enable.

**Comment by dnvriend** [comment]
I just wanted to give you kudos for chapter 2, I really enjoyed reading it while doing the review and wanted to let you know that. Great stuff! Keep up  the good work!

**Comment by cmbaxter** [comment]
Thanks Dennis.  Glad you like it so far.  Chapters 3-5 have been interesting for me as DDD and Event Sourcing are not core proficiencies for me.  Hopefully the content is accurate and informative.  Let me know when you get a chance to read it.

**Comment by dnvriend** [comment]
Most developers have a hard time with DDD and Event Sourcing, that's why this book will be so good!  Did you have a look at [Youtube - Field guide to DDD/CQRS using the Scala Type System and Akka by Renato Cavalcanti](https://www.youtube.com/watch?v=fQkKu4tTgCE)? Very good explanation of the topic.

**Comment by cmbaxter** [comment]
Ya, I listened to a few parts from that after you sent it.  He's definitely going for a more detailed DDD/Event Sourced/CQRS implementation.  I think the type safety part, having the sender of the command know that the receiver can handle it, is something my code is missing.  His is far more structured than mine.  The max page count is a tough constraint to deal with.  These chapters could easily be 100 pages and have a very rich and detailed implementation built within them, but that just can't happen.  I'm hoping that the small taste I am giving will be enough to get people over the hump so that they start to explore these concepts on their own a bit more.

**Comment by dnvriend** [comment]
You are absolutely right. Like the speaker said, there is a lot of theory to DDD/CQRS and if the book can show how to create a simple DDD model or refactor to one the reader will look for more information on her own.

**Pull request merged**
